version: "3"

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: ${INTERNAL_SUBNET}/12

services:
  wireguard:
    depends_on: [pihole] #[unbound, pihole]
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-UTC} # Change to your timezone
      - SERVERPORT=51820
      #- SERVERURL=my.ddns.net #optional - For use with DDNS (Uncomment to use)
      - PEERS=1 # How many peers to generate for you (clients)
      - PEERDNS=${PIHOLE_ADDR} #10.2.0.100 # Set it to point to pihole
      - INTERNAL_SUBNET=${INTERNAL_SUBNET} #10.6.0.0
      
    volumes:
      - ./wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    dns:
      - ${PIHOLE_ADDR} #10.2.0.100 # Points to pihole-unbound
      #- 172.16.100.200 #10.2.0.200 # Points to unbound
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

    restart: unless-stopped
    networks:
      private_network:
        ipv4_address: ${WIREGUARD_INTERNAL_ADDR} #10.2.0.3
  
  pihole:
      container_name: pihole
      image: cbcrowe/pihole-unbound:latest
      hostname: ${HOSTNAME}
      domainname: ${DOMAIN_NAME}
      #ports:
      #  - 443:443/tcp
      #  - 53:53/tcp
      #  - 53:53/udp
      #  - ${PIHOLE_WEBPORT:-80}:80/tcp #Allows use of different port to access pihole web interface when other docker containers use port 80
        # - 5335:5335/tcp # Uncomment to enable unbound access on local server
        # - 22/tcp # Uncomment to enable SSH
      environment:
        - FTLCONF_LOCAL_IPV4=${FTLCONF_LOCAL_IPV4}
        - TZ=${TZ:-UTC}
        - WEBPASSWORD=${WEBPASSWORD}
        - WEBTHEME=${WEBTHEME:-default-light}
        - REV_SERVER=${REV_SERVER:-false}
        - REV_SERVER_TARGET=${REV_SERVER_TARGET}
        - REV_SERVER_DOMAIN=${REV_SERVER_DOMAIN}
        - REV_SERVER_CIDR=${REV_SERVER_CIDR}
        - PIHOLE_DNS_=127.0.0.1#5335
        - DNSSEC="true"
        - DNSMASQ_LISTENING=single
      volumes:
        - etc_pihole-unbound:/etc/pihole:rw
        - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
      restart: unless-stopped
      cap_add:
      - NET_ADMIN
      networks:
        private_network:
          ipv4_address: ${PIHOLE_ADDR}